export default {
  content: ['./src/html/**/*.html', './src/js/**/*.js'],
  css: ['./src/css/**/*.scss', './src/css/**/*.css'],
  rejected: true,
  rejectedCss: true,
  fontFace: true,
  keyframes: true,
  // variables: true,
  safelist: {
    standard: [
      /(swiper|pagination|button|scrollbar|pagination-bullet|lazy|notification|preloader)/,
      /^swiper-/,
      'glightbox-open', 'glightbox-closed',
      /^glightbox/, /^g/, /^desc/, /^zoom/, /dragging/,
      /fullscreen/, /loaded/, /visible/, /current/,
      /inactive/, /prev/, /next/, /active/,
    ],
    deep: [

      /swiper-/,
      /^glightbox/,
      /^gslide/,
      /^ginner/,
      /^gloader/,
      /^goverlay/,
      /^gcontainer/,
      /^gclose/,
      /^gprev/,
      /^gnext/,
      /^desc-top/,
      /^desc-left/,
      /^gfadein/,
      /^gfadeout/,
      /^gbtn/,
      /^gabsolute/,
      /^grelative/,
      /^greset/,
      /^gzoomIn/,
      /^gzoomOut/,
      /^zoomed/,
      /^ginlined/,
      /^iframe/,
      /^swiper/,
      /faq-active/,
      /tooltip/,
      /anim/,
      /navmenu/,
    ],
    greedy:  [
      /swiper-/,
      /^glightbox/,
      /^gslide/,
      /^ginner/,
      /^gloader/,
      /^goverlay/,
      /^gcontainer/,
      /^gclose/,
      /^gprev/,
      /^gnext/,
      /^desc-top/,
      /^desc-left/,
      /^gfadein/,
      /^gfadeout/,
      /^gbtn/,
      /^gabsolute/,
      /^grelative/,
      /^greset/,
      /^gzoomIn/,
      /^gzoomOut/,
      /^zoomed/,
      /^ginlined/,
      /^iframe/,
      /^swiper/,
      /faq-active/,
      /tooltip/,
      /anim/,
      /navmenu/,
    ],
  },
}
