export default {
  extends: ['stylelint-config-standard-scss'],
  formatter: 'compact',
  threads: true,
  failOnError: true,
  fix: true,
  files: 'src/{css, scss}/**/*.{css, scss}',
  ignoreFiles: [
    'node_modules/**/*',
    'dist/**/*',
    'assets/**/*',
    'pagefind/**/*',
  ],
  plugins: [
    'stylelint-gamut',
    'stylelint-plugin-logical-css',
    'stylelint-use-nesting',
    'stylelint-plugin-defensive-css',
    'stylelint-media-use-custom-media',
  ],
  rules: {
    'selector-id-pattern': '[a-z]+(-[a-z]+)*',
    'selector-class-pattern': '[a-z]+(-[a-z]+)*',
    'gamut/color-no-out-gamut-range': true,
    'plugin/use-logical-units': [true, {severity: 'error'}],
    'csstools/use-nesting': 'always',
    'plugin/use-defensive-css': [true, {severity: 'error'}],
    // 'function-disallowed-list': ['rgba', 'hsla', 'rgb', 'hsl'],
    'color-function-notation': 'modern',
    'plugin/use-logical-properties-and-values': [true, {severity: 'error'}],
    'no-invalid-double-slash-comments': null,
    'property-no-unknown': null,
    'no-duplicate-selectors': null,
  },
}
